### ISSUE TITLE
Open a project or any image make app to crash

### ISSUE THREAD

**Issue by freMea** [NickeManarin/ScreenToGif#110]
I juts tested the app v2.6 in Windows 10 pro x64 (french) with last updates.

I saved a project and close the app. Later I open the project and the app crash.

Here is the [log]( https://gist.github.com/freMea/ebbde250e8a16c665490fdd7c714a5dd).

Here is the [project](https://drive.google.com/open?id=0B6fsosFSSxYZMGpuWTM5Smx6b0E).

So unzip the project and try to open one of its image. Crash again. I don't seem to be able to open anything without crashing the app.

Hope you can fix it.

**edit**: I fix it. I have to go to settings and delete the temp folder before opening some media. But it is still a bug.

**Comment by NickeManarin** [comment]
Hi, I could not reproduce this bug with v2.6 but I believe that it got fixed because of a previous issue related to opening/loading projects or images.

By the looks of it, this code throws the exception:

    Path.Combine(UserSettings.All.TemporaryFolder, "ScreenToGif", "Recording", RelativePath);

Specially because the first parameter was null (not set), but I don't know why exactly.

[ScreenToGif 2.X Preview.zip](https://github.com/NickeManarin/ScreenToGif/files/853671/ScreenToGif.2.X.Preview.zip)

Could you download this attachment and test if you notice the same behavior?

**Comment by freMea** [comment]
Thanks. It seems I can not reproduce this bug with v2.6 again. Don't know what happened then. Maybe because I changed the default user settings location to app folder during the session I saved as the project. Next I quit the app and later the crash occurred when I tried to open that project.

It's just an idea.

**Comment by NickeManarin** [comment]
Oh, that explains it. :)

When you delete a settings file, the current instance of the app keeps alive your latest settings until you close the app.

After opening the app again with the settings erased, the property `TemporaryFolder` (that holds the location of the recording files) was empty/null.

The bug here is that the Editor wasn't using the default value for the `TemporaryFolder` like the Recorder does when that property is empty.

To import a project or record something that values is obligatory, if there's no value for that, the app crashes. But now this bug is fixed. 

Thank you for your feedback and your kind words. :D
