### ISSUE TITLE
Artifacts with using gifs in MS PowerPoint

### ISSUE THREAD

**Issue by Sha-Grisha** [NickeManarin/ScreenToGif#122]
There was a conference..
I have created some gifs and and put them into MS PowerPoint 2016 presentation.
It worked normally on my laptop.
Some other people also have created and put them into MS PP 2016 presentation. Some of them used this program, some used another.
On the conference all used one PC with MS PP 2016.
All gifs, that were created in ScreenToGif, had artifacts however that were created in another program hadn't.
The artifact is, that some places, that were being fast changed, became white for some time...
(sorry for my English)

**Comment by NickeManarin** [comment]
I understand. Do you have an example? (a gif with the artifacts)

**Comment by Sha-Grisha** [comment]
Here is 4 files, 2 examples, original file and gif of how broken gif looks in PP (gifs were made via ScreenToGif =) )

![1 from powerpoint](https://cloud.githubusercontent.com/assets/25978914/25305481/547aeb7c-2795-11e7-8877-1dc7e9b81f76.gif)
![1 orig](https://cloud.githubusercontent.com/assets/25978914/25305482/547b247a-2795-11e7-918e-ac6a41ee5631.gif)
![2 from powerpoint](https://cloud.githubusercontent.com/assets/25978914/25305483/547da4f2-2795-11e7-8cdb-67cd19030b63.gif)
![2 orig](https://cloud.githubusercontent.com/assets/25978914/25305484/547f66fc-2795-11e7-9d1f-dc3239505873.gif)

P.S. Videos n the gifs are started from different place
P.P.S. ScreenToGif is awesome! =)

**Comment by vatterspun** [comment]
I'm not sure why this is happening but I would recommend using the video conversion tool.  You can run videos inside PowerPoint, even full screen.

![2017-05-04 18_23_44-screentogif - editor](https://cloud.githubusercontent.com/assets/1289134/25728791/e8ac915a-30f6-11e7-9207-a784f114c2ef.png)

**Comment by NickeManarin** [comment]
Hi, I tested with PowerPoint 2016 and it's working as expected. 😕 

I'm not sure if that particular version of PP (of the conference) was different than mine.

The artifacts that we can see with the examples are caused by an option of the encoder that could be not supported by PP. 

If that ever happen again, you can disable one or both options (in yellow):

![dis](https://user-images.githubusercontent.com/14798947/29098803-b8b60bd0-7c77-11e7-89df-4a4ebd8bc567.PNG)

Warning, this will increase the size of the gifs, not so noticeable with small recordings.

Also, you can try using the encoder 2.0 with the next release of the app (v2.9).
