### ISSUE TITLE
Add support to APNG

### ISSUE THREAD

**Issue by mlocati** [NickeManarin/ScreenToGif#129]
APNG is finally going to land on Chrome too ([reference](https://caniuse.com/#search=apng)).

What about adding support to it, in addition to .gif?

PS: [here's a sample APNG image](https://upload.wikimedia.org/wikipedia/commons/1/14/Animated_PNG_example_bouncing_beach_ball.png)

**Comment by panther2** [comment]
+1 for this request.

See [this demo](http://littlesvr.ca/apng/gif_apng_webp3.html)

**Comment by vatterspun** [comment]
Workarounds: 

1. Compose a GIF file in ScreenToGif and then compress using PNGOptimizer (http://psydk.org/pngoptimizer)
2. Record something and then save as project to a temporary folder.  Open the .STG file it creates with 7zip and compile them in an animated PNG using a compile program like APNG Anime Maker (https://sites.google.com/site/cphktool/apng-anime-maker).

**Comment by mlocati** [comment]
Since this wonderful app seems to work with frames in PNG format, I think it could be quite easy to integrate http://apngasm.sourceforge.net into ScreenToGif

**Comment by vatterspun** [comment]
Oh and I forgot to mention: one reason to use animated PNG over animated GIF is quality.  Animated GIF only accepts 256 colors while PNG supports.  You can see a very clear example of this in software slideshow: 

https://imgur.com/gallery/N4MzwAd - Animated PNG
https://imgur.com/gallery/eeSoS - Animated GIF (look at the very grainy cancel button)

Why this happens: "When converting an image from the PNG format to GIF, the image quality may suffer due to posterization if the PNG image has more than 256 colors." https://en.wikipedia.org/wiki/Portable_Network_Graphics#Graphics_Interchange_Format_.28GIF.29

**Comment by NickeManarin** [comment]
Done!

Should be available with the next release, v2.11

**Comment by vatterspun** [comment]
Ah fantastic news, thanks for that.

**Comment by vatterspun** [comment]
So by way of reference, some notes about Animated PNG and Animated GIF ...

All of the following are recordings made by clicking on a few buttons on the _screentogif.com_ homepage.  ScreenToGif was used to generate them and the last two images were run through a second program PNGOptimizer (http://psydk.org/pngoptimizer ... also an open source program) that compresses PNG files and converts GIF files (both animated and static).

----

**File 1** (66 k): GIF file.  You'll notice that it doesn't have the same color depth as GIF files are restricted to 256 colors.

![1](https://user-images.githubusercontent.com/1289134/34332788-85e2008e-e8fa-11e7-959a-29ca3ef7e1bb.gif)

**File 2** (91 k): PNG file.  Not smaller than the GIF file because it has a much wider color range.

![2](https://user-images.githubusercontent.com/1289134/34332792-8a76f41a-e8fa-11e7-98e8-29e167188527.png)

**File 3** (80 k): File 2 with PNGOptimizer.  About 10% smaller than before.

![3](https://user-images.githubusercontent.com/1289134/34332793-8e55a07c-e8fa-11e7-9973-335fb8195126.png)

**File 4** (46 k): File 1 saved using PNGOptimizer, which converts the animated GIF (File 1) to animated PNG .  The conversion results in a file that's about 30% smaller and almost half the size of the compressed PNG (File 3).

![4](https://user-images.githubusercontent.com/1289134/34332799-91d45df6-e8fa-11e7-9fe3-d9e8127d9eee.png)

**Results**: This was about what I was expecting and shows some of the strengths and limitations of the APNG vs. GIF format.

**Comment by vatterspun** [comment]
Oh and one final note, Github doesn't currently accept files that end with .APNG.

**Comment by Kristinita** [comment]
> Oh and one final note, Github doesn't currently accept files that end with .APNG.

@vatterspun possibly, it helps for you:

1. I create `.apng` in ScreenToGIF,
1. I load `.apng` file to Imgur,
1. I copy link to my file from Imgur,
1. I insert link with `.png`, not `.apng` extension to GitHub.

**Example**:

**Markup**:

```markdown
![APNG](https://imgur.com/6ilYB3M.png)
```

**Result**:

![APNG](https://imgur.com/6ilYB3M.png)

Thanks.

**Comment by NickeManarin** [comment]
@vatterspun Indeed, instead you can select to export as *.png.
