### ISSUE TITLE
Tweak temporary file management logic

### ISSUE THREAD

**Issue by ralienpp** [NickeManarin/ScreenToGif#195]
I have had some issues with Screen2Gif, it kept crashing out of the blue, though it worked well the day before. After trying out many things, going back to an older version - the problem persisted. 

Eventually I noticed that it is a problem with free space (lack thereof). After freeing up 6 GB on the volume, Screen2Gif worked for a while and then kept crashing again. I was back to no free space.

Upon further inquiry, I found that `%TMP%\Screen2Gif` had 36 GB of stuff in it, and it included files that were successfully exported to `.stg` projects from within Screen2Gif earlier.

What I think it necessary:

- Warn about low free space
- Clean up the temporary directory after the program quits

**Comment by NickeManarin** [comment]
Currently, the only automated way to clean up the temp folder is by enabling the "Automatically remove old projects" (it's enabled by default). With this option enabled, project older than 5 days will be deleted (during the startup of the editor).

I know that the ActionStack ('undo' and 'redo') takes a lot of disk space and I just adjusted the app to clear those files after closing a project (since they are not loaded next time the project is opened).

Also, just to check, are you running a version greater than v2.8.1? 
Because v2.8 had a bug with the process that erases the temp files.

**Comment by NickeManarin** [comment]
I added the option for automatically erasing projects, with a configurable maximum age in days. For example, you can set to erase projects older than 1 day.

Also, the app will warn about the free space. 

This changes will be available with v2.12 or 2.11.1
