### ISSUE TITLE
How do I put the frames on the sidebar like in previous version?

### ISSUE THREAD

**Issue by azmodai** [NickeManarin/ScreenToGif#209]
I recently used your W7 version, where all of the frames were nice and tight on the left sidebar, and now on W10 theyre fukk hueg on the bottom. This is a problem for me, I want them much much much tighter, just single checkboxes like previously. How do I do this, and if its not possible are you going to implement it again?

**Comment by NickeManarin** [comment]
The old version (v1.4.2 and older) had the list of frames to the left, without pictures.
The new version (v2.0 and newer) has the list of frames on the bottom, with the pictures. and it's not possible to change this.

Currently, I don't plan on using the old list without the frame preview again. I may change how the timeline works in the future, in order to accommodate multiple layers. But I won't go back to the previous style.

**Comment by azmodai** [comment]
Alright, thank you for your answer. Is there any place that I can download the older version of your software?

**Comment by NickeManarin** [comment]
The older version is not available anymore. The code is still available, but there's no download link. The last version is v1.4.2.

There's a bunch of ways to work with the frame list:

- <kbd>Ctrl + Shift + Left/Right</kbd>: Will select all the frames while you keep navigating with the arrow keys.  
- <kbd>Ctrl + A</kbd>: Selects all frames.
- <kbd>Ctrl + I</kbd>: Inverts the selection, what is current selected gets the deselected, what was not selected gets selected.  
- <kbd>Ctrl + U</kbd>: Deselects all frames.  
- <kbd>Shift</kbd> and Click: Select all frames between the currently selected frame and the frame being clicked.
- <kbd>Home/End</kbd>: Navigates to the first/last frames.
