### ISSUE TITLE
Error with gif and title frame

### ISSUE THREAD

**Issue by remyslab** [NickeManarin/ScreenToGif#216]
Version 2.10
Windows 10 64bits
Error with the portable app and the installed app.

I've got an error during the gif creation when I add a Title Frame. 

Title frame : title
Arial font
Normal values
Size 40
Black text
100ms delay
Center, center, 0 margin
White background

Error log : 
OutOfMemoryException
```
à System.Drawing.Bitmap.Clone(Rectangle rect, PixelFormat format)
à ScreenToGif.ImageUtil.ImageMethods.PaintTransparentAndCut(List`1 listToEncode, Color transparent, Int32 id, CancellationTokenSource tokenSource)
à ScreenToGif.Windows.Other.Encoder.Encode(List`1 listFrames, Int32 id, Parameters param, CancellationTokenSource tokenSource)

```
**System.Drawing.Clone**

Thanks,

**Comment by NickeManarin** [comment]
Thanks for the feedback.

By understanding the log that you gave me, this error happened when analyzing the frames, right before the gif encoding.

This OutOfMemory exception at the Clone() method usually happens if the rectangle is out of bounds. For example, if the frames don't have the same size.

Could you share that project with me? If you have sensitive data, you can create another one, adding the title frame.

**Comment by remyslab** [comment]
@NickeManarin 
I found something. This bug appears only when : 
- You down-scale dpi (to 72 in my case), and after you will add a title frame.
But if you add first the title frame, and you down-scale to 72 dpi, it's ok.

**Comment by NickeManarin** [comment]
Oh, ok. The title frame isn't respecting the current dpi of the project. Thanks.

**Comment by NickeManarin** [comment]
With v2.11 I can't reproduce this bug. I did some changes with the previewer, so I guess it was fixed.
