### ISSUE TITLE
Is it possible to upload to Microsoft Store as a UWP application?

### ISSUE THREAD

**Issue by zongren** [NickeManarin/ScreenToGif#218]

**Comment by NickeManarin** [comment]
Do you mean as a 'project centennial' app? If so.... Yes, but I can't do that without an authorization from Microsoft.

**Comment by vatterspun** [comment]
Wait, is the program in the Microsoft Store in any format?  Not just a "universal" app or whatever UWP is?

**Comment by NickeManarin** [comment]
No, not yet.

**Comment by vatterspun** [comment]
> not yet

I do not like Microsoft Store and most App Store setups in general, but I acknowledge that some locked-down computers will only download from Microsoft-approved download servers.  As a result, it's useful for some users who otherwise won't be able to use your program and it might help with virus false-positive issues in new releases (by over-paranoid AV tools).  Still, it's far from critical.
