### ISSUE TITLE
SVG

### ISSUE THREAD

**Issue by JacobLiou** [NickeManarin/ScreenToGif#219]
Can i ask how to create simple but effective SVGs? Like the ones in Viewboxs? how to put them into resources dictionary

**Comment by NickeManarin** [comment]
The vectors that I use in `Viewbox` elements are a bunch of `Path `+ `Canvas`, they are called "XAML Vectors".

One simple way is to use Inkscape, since you can directly export as XAML without any plugins.

[You can read about the other options here.](https://weblogs.asp.net/jongalloway/inkscape-to-support-xaml-export)

**Comment by vatterspun** [comment]
Yeah I was just going to say that SVG tools in a GIF editor is probably out-of-scope.
