### ISSUE TITLE
Something wrong with Chinese (Simplified)

### ISSUE THREAD

**Issue by Rebuilding127** [NickeManarin/ScreenToGif#226]
I used ScreenToGif not long before and I liked it all at once.
Today, I found a Chinese (Simplified) mistake when I was using it .
I want to enter is "处", but it is a wrong word that does not exist.
the right is 「夂卜」, the wrong is 「夂人」

**Comment by NickeManarin** [comment]
I'm sorry, but I didn't understand. 

Do you mean that the there's a wrong word in the Chinese (Simplified) translation or that while typing something on a text box inside the app, the wrong word appeared?

**Comment by Raka-loah** [comment]
Not a bug actually. 

The default font for Caption/Free Text is set to "Segoe UI", but this font doesn't contain Chinese characters, so every Chinese character will be forced using a "fallback" font, and causing this problem because... Asian things. (Same character has up to four different writing styles, Simp. Chinese/Trad. Chinese/Korean/Japanese, sometimes Windows will mess things up)

Simply change it to a font which supports Chinese characters (e.g. Microsoft Yahei), and it's "fixed" in no time.

**Comment by NickeManarin** [comment]
Alright, workaround for this issue is to select a compatible font.
