### ISSUE TITLE
Snap to window(drag and release to snap) doesn't work with vscode.

### ISSUE THREAD

**Issue by alpgul** [NickeManarin/ScreenToGif#236]
I can't select only text area.
![2018-01-12-12-53-36](https://user-images.githubusercontent.com/5773704/34869398-d5684248-f797-11e7-9134-00c8c94493b3.png)

**Comment by NickeManarin** [comment]
I'm slowly transitioning from this UI to the new one (you can enable that new UI by opening Options > Application and checking the "Enable the new recorder UI").

The new version of the recorder has a more consistent window selection mode.

**Comment by alpgul** [comment]
the new ui can't choose like the old ui. The program can't fully select the window. The program can't auto-select columns in window. Example: Explorer panel, text view panel, preview panel

**Comment by NickeManarin** [comment]
Indeed, the new recorder UI cannot select parts of the screen.

Also, I downloaded and used the "Snap to Window" feature and it works as intended. If you drag the button and drop it on top of the title bar, the whole window will be selected.

But it does not work if the VS Code window is maximized (I just noticed on your screenshot), because there's no space left for the Recorder window to fit. You can try enabling the "Thin mode" of the recorder, by right-clicking the "Record" button.

**Comment by alpgul** [comment]
If "Thin mode" is active I can choose whole screen except the title. Do you have any solution for parts of the screen?

**Comment by NickeManarin** [comment]
What do you mean by " I can choose whole screen except the title"?

The "thin mode" only makes the Recorder interface a little bit smaller, by hiding the titlebar. You can still use the same way as if the "this mode" was off.

**Comment by NickeManarin** [comment]
Due to how Visual Studio Code render its UI (it's a Electron app), ScreenToGif can't detect each part of its UI separately.

**Comment by flywire** [comment]
> The screen recorder is composed of a hollow window with the main controls on the bottom. From the left to the right:
> * Snap to Window: Click, drag and drop on top of a window to automatically resize and move ScreenToGif to fit.

Not working if you drag the screen recorder window and drop it on top of the required window title bar.

Win10 64-bit, ScreenToGif V: [2.25](https://github.com/NickeManarin/ScreenToGif/releases/tag/2.25)
