### ISSUE TITLE
progress > text > percentage > wrong values

### ISSUE THREAD

**Issue by Shemesh** [NickeManarin/ScreenToGif#270]
hi,
go to: image > progress > text > percentage > remove the "show total value". and apply.

watch the values, they are wrong, displaying in THOUSANDS.

**Comment by NickeManarin** [comment]
Right, it's assuming the current installed culture of the UI.

**Comment by Shemesh** [comment]
sorry, v2.13, problems remain.
see attached animated gif:
top-left is: percentage > remove the "show total value"
bottom-right is: custom > `$p%`

plus - ux wise - when showing percentage there is no need to show fractions, e.g. 32.4... 76.9..
it is too much information. showing integers is better.

![s2g](https://user-images.githubusercontent.com/2488980/37817223-26b2ebd2-2e87-11e8-92bb-89edb3f671f8.gif)

**Comment by ashleedawg** [comment]
[<img src="https://user-images.githubusercontent.com/29980309/39671685-1491573c-50d2-11e8-8504-acb808985b0f.png" height=150>](https://user-images.githubusercontent.com/29980309/39671685-1491573c-50d2-11e8-8504-acb808985b0f.png)

Hi @NickeManarin - just FYI, there's still the issue of the %progress being out by 100×.  

However, I disagree with the suggestion that the value be truncated to zero decimal places, since the fraction is relevant if the project is >100 frames.  Perhaps the number format could be `if (frames>100) {"0.0%"} else {"0%"}`?  (The user could still use the custom format for a truncated value, or vice-versa.)



---
@Shemesh - In the meantime you can also display the progress percentage (without the total) like this:
 - [x] **<kbd>Alt</kbd>+<kbd>K</kbd>** (or click `Image `→ `Progress`), and set: 

   Setting|Value
   -------|-----
   Type|`Text`
   Precision|`Custom`
   Format|`$p%`

 - [x] Then, hit <kbd>Enter</kbd>  to apply the change (or click `Apply`.)

 - [ ] Other custom formats can be viewed by hovering your mouse over the _Format_ box.


<sub><sub>In case you couldn't tell, I'm just learning (and practicing) [**GitHub-flavoured markdown**](https://guides.github.com/features/mastering-markdown/#syntax)...  Forgive me!  :nerd_face:  </sub></sub>

**Comment by NickeManarin** [comment]
Ok, I was able to fix this.
