### ISSUE TITLE
Can't import a video file to ScreenToGif（无法载入视频文件）

### ISSUE THREAD

**Issue by realzzc** [NickeManarin/ScreenToGif#283]
Hi~

When I start a project by importing a video file to ScreenToGif. The Program will getting into a no-end loading. I confirm that my PC has installed 4.7.1 .NET Framework with Windows 10.And I have tried a lot of video files，they all do not work.Please help~ 

![2018-03-06_19-54-33](https://user-images.githubusercontent.com/18380597/37031032-38c4dc3e-2178-11e8-85aa-144187974f50.png)

**Comment by NickeManarin** [comment]
Do you have Windows Media Player enabled on your system?
The media element that displays the video requires that app.

**Comment by realzzc** [comment]
Yes，I have enabled the「Media Features」on my system，but it still not work

![default](https://user-images.githubusercontent.com/18380597/37506203-b24fd8e4-2923-11e8-85fe-e931e98bb4f4.png)

**Comment by NickeManarin** [comment]
The thing is, that Windows Media Player should exist in your computer for it to work. It's under `Media Features > Windows Media Player`.

Since there's no children option in your screenshot, I'm assuming that you are using Windows N or K, which don't have WMP bundled.

In v2.20, I've added a new method for importing frames from videos, by using FFmpeg. I also added error messages, to warn the user that something is not working.
