### ISSUE TITLE
For auto language 

### ISSUE THREAD

**Issue by laiqun** [NickeManarin/ScreenToGif#288]
could you use
"System.Threading.Thread.CurrentThread.CurrentCulture.Name"
instead of  "CultureInfo.InstalledUICulture" for auto language detection?

**Comment by laiqun** [comment]
The different between those ，already be discussed in this url：
https://stackoverflow.com/questions/329033/what-is-the-difference-between-currentculture-and-currentuiculture-properties-of

**Comment by scoutboy420** [comment]
If you mean what is happening in LocalizationHelper.cs after clicking on Autodetected language in Language options, then we need to use CultureInfo.InstalledUICulture, because it's the only one that always provides specific cultures (such as pt-BR as opposed to just pt). We have defined our own language codes management, so sometimes specifics are needed, sometimes neutrals. But we always should start from specifics. When we have a specific culture and there is a resource file for that culture, then we are good to go. If there is no resource file for that culture, we can check for parent culture (which is always neutral culture, for example, pt is the parent of pt-BR) and check if we have a resource file for that. Again, if we have that's great, but otherwise (which means that language is unsupported) we switch to the English language, which is always present and ready to use.
