### ISSUE TITLE
Tray icon issues

### ISSUE THREAD

**Issue by user3323** [NickeManarin/ScreenToGif#298]
1) color issue

white on white - not the best choice)
it was really hard for me to find out where is the icon... really

![image](https://user-images.githubusercontent.com/24613274/37576183-c6f0b27a-2b33-11e8-916c-fc86a6f75b5f.png)

2) looks very similarly with "network connection" icon
![image](https://user-images.githubusercontent.com/24613274/37576278-5eee3282-2b34-11e8-98dc-d853bd1ea4ff.png)

3) mouse LEFT button clicks
no reaction at all - neither for single click, not for double
it should open the last closed window..
would it be single or double - your choice

4) there is no need to allow STG make new copies of itself (2nd, 3rd, etc.)
so when a user trying to start already launched STG - the last active window should be opened
![image](https://user-images.githubusercontent.com/24613274/37576747-74983ebe-2b36-11e8-9506-0a268092ddff.png)

5) when my recording window is active and I want, for example, make a new "Webcam recording" - I cannot - all three buttons in the context menu are disabled

![image](https://user-images.githubusercontent.com/24613274/37576841-00323452-2b37-11e8-8fa6-0b02e291c7d8.png)

6) do you want to exit?
you've implemented options for these annoying questions in the options.
can you also make an option for this one?
so I could disable it and do not press YES every time

Thanks!

**Comment by laiqun** [comment]
Yeah,this is the issue I want to description.

**Comment by laiqun** [comment]
@ your explaination is very interesting ，Belly laugh

**Comment by NickeManarin** [comment]
1) Alright, when designing the icon, I only had in mind Windows 10. I'll create an icon for other version of the OS.

2) Humm, it's a wireframe version of the logo of this app. I'm using this style because it matches the OS design.

3) Ok, I'll think about this. Maybe I'll make it configurable.

4) This touches a grey area. It's the only way to open two recorder instances. Maybe I'll add an option to let this happen, but making it default to give focus to an already opened instance.

5) I disable the other recorders by design. Currently the keyboard watcher (that works for detecting keyboard presses) only allows one usage per instance. I need to change the code under the hood in order to allow multiple recorders. 

6) Yes. I'll create and option for that one too.

**Comment by smaragdus** [comment]
Just a remark, when I first started version 2.13 the tray icon appeared in the hidden part of the system tray and it was invisible until I hovered the mouse pointer over the blank space.

**Comment by NickeManarin** [comment]
6. Done.

**Comment by NickeManarin** [comment]
3. Done!

![Application](https://user-images.githubusercontent.com/14798947/69020667-17f58e80-0994-11ea-95eb-1d44488626d9.png)

You can test here if you wish: https://github.com/NickeManarin/ScreenToGif/issues/551

4. I'll track this suggestion in another issue ticket.
