### ISSUE TITLE
Gifski encoding is failing when using non-latin characters

### ISSUE THREAD

**Issue by u2shana** [NickeManarin/ScreenToGif#323]
how can i use gifski

**Comment by u2shana** [comment]
WIN7 it work

**Comment by NickeManarin** [comment]
Did you download the Gifski dll via the Options > Extras > "Download Gifski" button?

**Comment by u2shana** [comment]
Yes,but it didn't work in win10

**Comment by NickeManarin** [comment]
Can you show me a screenshot of the error?

**Comment by u2shana** [comment]
No error info,just stuck when encoding,and then the program disappear
![xyuptl ky8iduz32wnta](https://user-images.githubusercontent.com/14146754/40264157-95afa3b8-5b50-11e8-810d-6ad20ca18d3b.png)

**Comment by NickeManarin** [comment]
Hmm, without an error message this will be hard to be solved.
From what I can see, it's stuck on the first step of the encoding, like something is blocking from even starting.

Please, check if the Dll file is not being blocked by some anti-virus. Also, check if it's not marked as "Downloaded from the internet" (If you right click on the DLL, open Properties, check if there's a button that says something like "Unblock").

**Comment by u2shana** [comment]
Emmm,I used the same program and same gifski.dll in win10 1605.It encoding successed.
I'm sure the dll is not be block in my PC.

**Comment by u2shana** [comment]
Oh,I change the cache folder in other path which don't contain chinese(because the default path contain a chinese user name).Then,the Gifgski work.

**Comment by NickeManarin** [comment]
Oh, that explains it. Thanks :)

**Comment by Kristinita** [comment]
### 1. Summary

Gifski doesn't work, if in path Non-ASCII symbols, not only Chinese.

[**See also**](https://github.com/NickeManarin/ScreenToGif/issues/115#issuecomment-373577822).

### 2. Data

+ [**Project file**](https://drive.google.com/open?id=1oKn0nxeg0uifDukejU-wLfRlHtIdHclI)

### 3. Steps to reproduce

I open project in ScreenToGIF → `Save as` → `Gif` → `Gifski`.

### 4. Expected behavior

**If** folder name:

+ `D:\ScreenToGIF`

**or**

+ `D:\Screen To GIF` (use breaking spaces)

    GIF successfully created:

![GIF expected](https://i.imgur.com/s3uS16U.png)

### 5. Non-expected behavior

**Else** folder for saving name:

+ `D:\СкринТуГиф` (all letters — Cyrillic)

    ScreenToGIF crash. No logs.

![ScreenToGIF crash](https://i.imgur.com/v8ckjHE.png)

### 6. Environment

+ Windows 10 Enterprise LTSB 64-bit EN
+ ScreenToGIF 2.16
+ Gifski — download from `Extras` → `Options` → `Extras` → `Gifski`

Thanks.

**Comment by clickwithclark** [comment]
gifski suddenly not working for me, here is the log of the error

----------------------------------

► Title - 
	Encode
▬ Message - 
	The type initializer for 'ScreenToGif.Util.GifskiInterop' threw an exception.
○ Type - 
	System.TypeInitializationException
♦ [Version] Date/Hour - 
	[2.17.1] 05/05/2019 20:23:49
▲ Source - 
	ScreenToGif
▼ TargetSite - 
	IntPtr Start(Int32, Boolean, Boolean)
♠ StackTrace - 
   at ScreenToGif.Util.GifskiInterop.Start(Int32 quality, Boolean looped, Boolean fast)
   at ScreenToGif.Windows.Other.Encoder.<Encode>d__23.MoveNext()

▬▬ Message - 
	Value cannot be null.
Parameter name: ptr
○○ Type - 
	System.ArgumentNullException
▲▲ Source - 
	mscorlib
▼▼ TargetSite - 
	System.Delegate GetDelegateForFunctionPointer(IntPtr, System.Type)
♠♠ StackTrace - 
   at System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer(IntPtr ptr, Type t)
   at ScreenToGif.Util.GifskiInterop..cctor()

----------------------------------

**Comment by NickeManarin** [comment]
@clickwithclark Can you try downloading Gifski again? Using the download button from Options > Extras.

**Comment by clickwithclark** [comment]
just did, just getting the error again.

**Comment by NickeManarin** [comment]
@u2shana @Kristinita @clickwithclark 
There's a new test version which should solve this bug.
Download here: https://github.com/NickeManarin/ScreenToGif/issues/551

Can you people test it?
In order to test it, you need to delete the old Gifski and download again via Options > Extras, while using the test version of ScreenToGif.

**Comment by JsBergbau** [comment]
Had just a similiar issue. You have to download gifski in the settings dialog. Downloading it from Website and pointing to that path fails when trying to create the gif with this error:
```
   bei System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer(IntPtr ptr, Type t)
   bei ScreenToGif.Util.GifskiInterop..ctor()
   bei ScreenToGif.Util.EncodingManager.<Encode>d__27.MoveNext()
```
