### ISSUE TITLE
Moving capture area to other monitors hides the toolbar

### ISSUE THREAD

**Issue by EraserKing** [NickeManarin/ScreenToGif#342]
ScreenToGif 2.13.3
Dual monitors
Windows 10 1803 (17034)

Open ScreenToGif - Recorder - (make sure capture method is Area) - move the capture area to the other monitor OR draw the capture area on the other monitor
Then, the toolbar (OK / Retry / Cancel) disappears. No way to confirm / cancel the new area, unless pressing Enter / ESC.

**Comment by NickeManarin** [comment]
How big was the area selected? If I remember correctly, the app moves the middle of the screen if there's not enough space available at the sides.

If is not in the middle, the app is trying to display the controls at the nearest available corner (nearest from the latest know interaction of the cursor).

Can you take a screenshot of all screens when this happens? 

Btw, those three actions are triggered by **Enter (Accept)**, **Right-Click (Retry)** and **Esc (Cancel)**.
_(So you can use the app while this bug is not yet fixed)_

**Comment by EraserKing** [comment]
![image 4](https://user-images.githubusercontent.com/1160403/41836024-0cf43a80-788c-11e8-8fda-80d8618fe7f3.png)

Actually it doesn't care how large the capture area is, a large one or a small one both can be used to trigger this bug... Additionally, I found it usually happened on my main monitor (the right one) when I tried to select an area, but I also met this on the other monitor before.

Shortcut Key works. Thanks.
