### ISSUE TITLE
Feature Request: Move recording area with the Cursor

### ISSUE THREAD

**Issue by mabbas64** [NickeManarin/ScreenToGif#418]
I used this feature in another recording application and it helps a lot when I want to keep a small recording video/gif dimension but need to show multiple further-apart sections of the screen. 

So e.g if i have a 600x400px wide recording area, this feature can allow moving the recording box automatically where ever my cursor goes on the screen.

**Comment by vatterspun** [comment]
It's a good suggestion that could show much more of a given screen with a drastically smaller file size.

Assuming this is something the author wants to spend time on, I think the the main thing with this suggestion is that the mouse cursor should not be perpetually in the CENTER of the screen during these recordings.  In my experience, these videos are really disorienting because you only ever pay attention to the mouse and everything else jumps around it.  Instead, it's ideal if the recording frame moves with the mouse only when the mouse approaches within approx 10 pixels of the window border.  In this way, the screen can move with the mouse, but you can still get some sense of what's happening on the screen.

I've used programs in the past that did both of these but struggled to find an example of both.  I'll post again if I can find one.

**Comment by vatterspun** [comment]
Update here: I found an example of mouse-follow in a freeware video: https://www.youtube.com/watch?v=_8AdC-qQZgI&t=375s (the content not so important as the method of recording)

I'm not sure what was used to record it, but you can see when the mouse shifts on the screen, it travels roughly 10 pixels before the frame follows it.

**Comment by TheJim01** [comment]
I was just looking for this option myself.

I think we can get the best of both worlds (buffered and lock-step), and that would be accomplished by @WELZ-gh 's idea of post-processing. It offsets a majority of the work from the recorder onto the editor. The only problem I foresee is that it would require the initial recording to capture the entire screen space every frame so it could perform the cropping later.

Meanwhile, the recorder _could_ encode a "follow" flag into each frame. Whether that flag is enabled throughout the entire recording, or only enabled by a hotkey at run-time, the post-processor could crop the frames based on the state of the flag.

For example:
1. User sets a record area of 300x300
2. User starts recording
3. User realizes they need to move to another part of the screen
4. User depresses `Ctrl`+`Q` (or something, doesn't matter)
5. The frame locks to the cursor (doesn't need to be centered)
6. User moves the cursor+frame to the new working region
7. User releases the hotkey
8. The frame unlocks from the cursor

This also allows the hotkey to control different types of following:
* Always follow except on hotkey
* Follow only while hotkey is pressed
* Hotkey toggles follow

**Comment by NickeManarin** [comment]
I'm working on this feature request and I'm currently implementing it like this:
(I may change it)

- Activates/Deactivates by pressing a key combo.
- UI is hidden during mouse movement, in order to avoid it getting in the way of the recording. (You can notice that if you move a recording window too fast and the FPS is low, parts of the UI will be captured too).
- The UI will tell you when this capture mode is enabled.

### Buffer mode
- Configurable buffer, percentage or fixed value, independent side buffers (x4).

### Always on center mode
- **This one poses an issue**, since the mouse can be always moving around, I must always hide the recorder.


> ![Following](https://user-images.githubusercontent.com/14798947/64310232-bc5f5b80-cf75-11e9-8154-4bf7791b846b.gif)
> Example of buffer mode (20px at both sides)

**Comment by qJake** [comment]
@NickeManarin  This looks fantastic! I can't wait for this!

I think, for your potential problem, you have 3-4 options:

1. Tell the user they have to press some special key combination to stop recording (Windows does something similar when screen recording from PowerPoint or in a game using the "game bar").
2. Put an icon into the system tray / notification area that the user can click to stop recording
3. Leave the UI on-screen but draggable, and if it shows up in the recording it's the user's fault they didn't move the UI
4. Some other screen capture devices do this - is it possible to "ignore" your own UI during capture? For example, in a Zoom meeting, when you share your screen other participants don't see your own UI controls.

I think even if you just shipped Buffer mode, it would make a bunch of people happy. Keep up the great work!

**Comment by labsforge** [comment]
Hi!

I was wonder if there is a possibility to set the bounds of the region that follows the mouse? I mean, if I only wan't to record inside an app, and don't want to catch things outside?

Thank you!

**Comment by NickeManarin** [comment]
@labsforge No, right now there's no way. :/

**Comment by jaxjexjox** [comment]
So this won't be added or can't?

Just want to vote that this feature I'd really like, sorry to re-open but I literally found this page, by googling "follow cursor" and screen to gif.

Thanks ofr hard work regardless

**Comment by NickeManarin** [comment]
@jaxjexjox Are you referring to the feature that @labsforge asked or the one that this issue ticket was created for?

If the first, create a new ticket and it will be implemented.

**Comment by jaxjexjox** [comment]
Nick,

I apologise, I didn't read the thread very well initially.

Should I make a new request or expand on this one? I'm slowly getting used to the program but I think my main gripe (sorry!) is that the 'snap to cursor' pixel buffer is only 100 pixels.  I kind of need something upwards of 150 to 200 pixels still, as I'm documenting stuff for some elementary users and I really and them to get a good understanding of what they're seeing.

I still would be curious to see the app do a 100% 1 to 1 snap to the cursor, even if it moves around the display a lot, just to get an idea of how that plays.

**Comment by NickeManarin** [comment]
@jaxjexjox I asked what you meant because this ticket was about a "cursor following" feature that already got implemented, but another user asked about the possibility to limiting the cursor following to a specific app.

So, I was confused about what you wanted.

Now I understand that you want an increased buffer zone limit.
I opened a new ticket for that: https://github.com/NickeManarin/ScreenToGif/issues/643

**Comment by Aetherinox** [comment]
Just in case anyone sees this (I'm still looking through the settings), but is their a way to force it to follow the cursor dead center (unless you move to the edge of a screen).

I've increased the buffer to 100, and it's better, but it's still only moving when the cursor is near the edge, and it's kind of disorientating.
