### ISSUE TITLE
Record pause when moving the recorder window

### ISSUE THREAD

**Issue by wvxwxvw** [NickeManarin/ScreenToGif#421]
Hi,
I noticed that when I call the recorder from the editor, when I move window around the screen, the recording stops. The result is that frames are captured before and after the movement and while driving, the recording pauses. With a simple recorder call, everything works correctly.

**Comment by NickeManarin** [comment]
This is an old bug. It happens with some machines, not with everyone. I still don't know what happens exactly.

**Comment by vatterspun** [comment]
Ha!  Actually when I first read this, I didn't think this was a bug.  I thought "yeah it might be nice for the program to automatically pause when moving the window."

**Comment by WELZ-gh** [comment]
@vatterspun when moving around it's actually smooth and continues recording, the bug happens when the recorder is launched from the Editor and not directly.

**Comment by NickeManarin** [comment]
I fixed this bug. 
It was caused by the code that saves the window position.
Strange that it only happened when calling the recorder from the Editor.
The window movement now feels a little bit lighter.

![image](https://user-images.githubusercontent.com/14798947/65800006-cf67e480-e14b-11e9-9d95-bf75c9322421.png)
