### ISSUE TITLE
Add shortcut support for the crop window？

### ISSUE THREAD

**Issue by ghost** [NickeManarin/ScreenToGif#455]
![2019-02-26_085527](https://user-images.githubusercontent.com/47240078/53379653-65b10d80-39a5-11e9-87db-cf74a902ede8.png)
Just like this, the image will be restored to the default size when cropped or blurred, and the enlarged image will adjust the selection more precisely.

**Comment by vatterspun** [comment]
Help me understand: the program has a fairly solid crop tool already - what did you want to be different?

**Comment by NickeManarin** [comment]
Done!

**Arrow keys**: Move the crop area around.
**Shift + arrow keys**: Resize the crop area based on the **bottom-right** corner.
**Ctrl + arrow keys**: Resize the crop area based on the **top-left** corner.
**Ctrl + Shift + arrow keys**: Resize the crop area based on all corners, left/bottom will reduce the size of the area, right/up will increase the size.

(You'll need to set focus, by clicking on the crop area in order to use any shortcuts)
