### ISSUE TITLE
Program Stops Responding While Entering File Name

### ISSUE THREAD

**Issue by DommDynamite** [NickeManarin/ScreenToGif#485]
OS: Windows Server 2012 R2

While typing in a file name, the program will go into not responding status for around 5-6 seconds before entering each letter.

**Comment by michael-milette** [comment]
OS: Windows 10
I have experienced something similar with very large video (about 10 minutes). As soon as I started entering the filename, it stopped responding. It took a while but it did eventually unblock after a few minutes and I was able to finish typing the filename.

**Comment by NickeManarin** [comment]
Can you two share with us the path and filename being used?

**Comment by NickeManarin** [comment]
Well, I changed the way that feature (that checks if a given filename exists already or not) works.
So instead of checking after every text change, the app will only make 1 check 500ms after the last letter that was typed.

**Comment by michael-milette** [comment]
I don't think it is relate to the actual filename. I noticed this becomes problematic with longer videos (animated GIFs). For example, I had one that started off being 15 minutes and I was editing it down to about 8 minutes.

This was not a problem with short 2-3 minute videos.

**Comment by NickeManarin** [comment]
Well, it makes sense that a longer recording would hang more than a small one, because there's more resources allocated to displaying more frames to the list. 

Btw, I forgot to ask. What filename textbox are you referring to? The one inside the Editor window or the one inside a "Save as" dialog from Windows itself? The second one I have no controls over.

Anyway, I changed the way that I'm checking if a filename was used or not because the old way was not good.

**Comment by michael-milette** [comment]
Thanks for fixing it. It was indeed the one in the editor window, not the Windows one.
