### ISSUE TITLE
Artifacts of moving windows when recording

### ISSUE THREAD

**Issue by andrecool-68** [NickeManarin/ScreenToGif#487]
If  disable the option "enable desktop composition" in windows 7 ...then these artifacts disappear
In windows 10 it's impossible to get rid of this artifact

enabled `enable desktop composition`

![000](https://user-images.githubusercontent.com/3471892/58660554-618ee600-832e-11e9-90b7-0f98c71da8d7.gif)

disabled `enable desktop composition`

![111](https://user-images.githubusercontent.com/3471892/58661333-50df6f80-8330-11e9-87cf-e1d123adb94c.gif)

**Comment by NickeManarin** [comment]
The artifact that you are seeing (second gif) are due to the color quantization process. It's only possible to reduce its effect when disabling the option to paint unchanged pixels with a dummy color (chroma key).

**Comment by andrecool-68** [comment]
@NickeManarin 
The artifact occurs on the first animation!
The second image is fine ... and there are no artifacts!

**Comment by andrecool-68** [comment]
@NickeManarin This artifact occurs during the screen recording process ... and not during the editing process.

**Comment by NickeManarin** [comment]
I can see artifacts in both gifs. I'm aware of the artifacts of the second gif, when you move the window, there's some pixels with the wrong shade of the color. This happens because of the gif encoder trying and failing to find the right color.

Now, the first gif shows a trail of the window border.  I'm not sure what's happening. Have you tried to disable that option, so when the window is dragged, it will move in place, instead of just the border.

I remember that got the same issue back when I was using Windows 7, specially when the computer was slow and the graphics adapter was not handling so well all changes.

**Comment by andrecool-68** [comment]
@NickeManarin In these examples only the window frame should be moved (without its contents!)
sorry me for my bad english

**Comment by NickeManarin** [comment]
@andrecool-68 So, you are saying that the window border is getting glitched like that only when recording?

**Comment by andrecool-68** [comment]
@NickeManarin 
Exactly! This happens already in the recording of the animation on the desktop.

**Comment by NickeManarin** [comment]
I think that you need to contact Notepad++ devs and show this issue to them. It's something out of my control.
