### ISSUE TITLE
Capture opens on wrong screen

### ISSUE THREAD

**Issue by psarno** [NickeManarin/ScreenToGif#528]
I have a Windows 10 laptop (1903, OS Build 18362.356) that is projecting to a monitor via HDMI (monitor 1) and its own screen (monitor 2).

When I run ScreenToGif the primary controls open on the monitor (1) and when I click "Recorder" those controls open on the laptop screen (2).

This is highly confusing, it should open on the same monitor as the executable at first unless otherwise moved by the user.

**Comment by NickeManarin** [comment]
Which version are you using?
Which recorder (older or newer)?

Both the Startup, Editor and Recorders save its position when closing, just to open again at the same spot. 
If you close the recorder while it was on the second monitor, it will appear again in that spot next time that you open.

Do you want an option to disable that feature? Or is it not working as expected?

**Comment by psarno** [comment]
> 
> 
> Which version are you using?
> Which recorder (older or newer)?
> 
> Both the Startup, Editor and Recorders save its position when closing, just to open again at the same spot.
> If you close the recorder while it was on the second monitor, it will appear again in that spot next time that you open.
> 
> Do you want an option to disable that feature? Or is it not working as expected?

Version 2.19.0.0.

I had a prior portable version installed that was used when I was not connected to a laptop screen (used single screen).

I now used it in both portable and the MSI version with the results described above.

**Comment by NickeManarin** [comment]
Sorry, I didn't ask properly.

The app has two screen recorders, the new one can be enabled via Options > Application > Enable new recorder UI. They are very different, so they behave differently. 

Now, the second question asks if the last time that you closed the recorder, it was positioned at the second monitor or not?
And if you really want that happening or not.

For example:

> The app is working as expected: You opened the recorder, moved to the second monitor than closed it. Next time, the recorder opened on the second monitor as expected.

> The app is not working as expected: You never closed the recorder while it was on a second monitor, but somehow the recorder always open on the second monitor.

So, given these two promises, I think that you want to: 

- Disable the feature that remembers the position of the recorders while they are getting closed.
- Fix the app, since the recorder was never moved to the second monitor, so it would not make sense that it would open at that position.

**Comment by NickeManarin** [comment]
The recorder was fully reworked.

The capture controls won't be moved to another screen anymore.
