### ISSUE TITLE
Conflict with the new library UI of Steam

### ISSUE THREAD

**Issue by byzod** [NickeManarin/ScreenToGif#545]
I have to use NVIDIA experience to capture the demo below

Screen To Gif: 2.17.1
Encoder: Gifski
Platform: Windows 10 1703 x64
Steam: 1572467527 (build time Oct 30 2019, 13:07:23)

---

Demo:

**Comment by byzod** [comment]
OK I can't edit the post nor upload the gif for unknown reason, please check the [demo here](https://imgur.com/hZmCSwj)

**Comment by NickeManarin** [comment]
I believe this is related to #183

**Comment by NickeManarin** [comment]
Wow, even worse, if you click on some title (it will not work), but after you close the recorder, the action will work (late). Thats... strange.

The same does not happen with the older recorder, that uses the same way to be transparent.

**Comment by NickeManarin** [comment]
I noticed that if the recorder window is on top of the area that web engine has to display its content, this bug happens. 

I believe that Steam uses Chromium, so that's a common denominator.
Any app that uses Chromium has this issue.
Chrome, Steam, MS Edge (the new one).
They all have this issue.

Even if the window has transparency. Which this app uses.

**Comment by Hrxn** [comment]
Yes, Steam, like Spotify, and a lot of other popular apps, use CEF (Chromium Embedded Framwork), but I guess it also depends on the settings for hardware acceleration.

**Comment by NickeManarin** [comment]
I filed a bug ticket in here: https://bugs.chromium.org/p/chromium/issues/detail?id=1025598

**Comment by NickeManarin** [comment]
They fixed it. Now we should just wait...
