### ISSUE TITLE
Allow Undo Buffer Disable

### ISSUE THREAD

**Issue by Crispin-at-Linknode** [NickeManarin/ScreenToGif#555]
Hi,

With large volumes of data I found that the auto-undo folder was leaving me out of disk space, for example with 4,000 images, removing 3,000 nearly doubled the space required temporarily.

Could a disk space calculation for undo be estimated, or I'd be happy with an option to make an informed decision to disable undo. perhaps on a per-session basis so it resets each time.

 Many thanks - Crispin

**Comment by NickeManarin** [comment]
Would a undo/redo limit help you? 
For example: 

- Keep only the last N actions stored.

**Comment by Crispin-at-Linknode** [comment]
Yes... as long as the limit could be set to zero!

With the example above, it is just a single operation to remove duplicates.  Would a limit be on the operation or the images saved in the undo folder?
I wouldn't really want to undo to a partial state if only half the images were restored on undo.

**Comment by NickeManarin** [comment]
If the limit is set to zero: 

- The app does not save any state and you can't undo/reset anything.
- All actions are permanent.

Now, if the limit is set for example, to 2:

- You delete a frame: Before deleting the frame, it's stored in the action stack (pile of actions that can be undone).
- You add a text on a frame: Before adding the text, the frame is stored in the action stack.
- You crop the animation: Before cropping, the whole project is saved in the action stack, since all previous frames are going to be altered. **After saving the state, the first action (oldest one) is removed from the stack and its files are deleted.**  
- If you try to undo all actions (by clicking Undo multiple times or by clicking on Reset), you'll be able to undo until reaching the "text on a frame" action. So, you won't be able to recover the deleted frame.

**Comment by NickeManarin** [comment]
Closing this as done.
