### ISSUE TITLE
Possibility to record only on Pixelchanges

### ISSUE THREAD

**Issue by dschiller** [NickeManarin/ScreenToGif#575]
Don't know how to create a Question here. Is it possible to record only if Pixel changes on Screen ?

**Comment by NickeManarin** [comment]
Right now, no. 
With the DesktopDuplication API is possible, but I didn't implement it that way for the next version.

Right now you can record normally and later remove duplicated frames using the "Remove Duplicated Frames" feature. 

Why do you ask?

**Comment by dschiller** [comment]
I ask because if recording long sessions to catch Errors for UI Automation it take a long time after stop recording and accessing the recorded Images. Would be much faster if already recording only changed Images.

**Comment by NickeManarin** [comment]
This could be implemented as a new capture mode, by using a feature from DesktopDuplication that tells which screen areas have a pixel change.

**Comment by NickeManarin** [comment]
Done! It will be available with the next version, 2.27.

It can be enabled when using DirectX capture mode.

![image](https://user-images.githubusercontent.com/14798947/89718684-12632d00-d997-11ea-9438-9c56bfd1afb0.png)

How does it work?

If something changed (pixels, including mouse cursor updates) within the capture region since the previous frame was captured, another frame will be captured.  

![image](https://user-images.githubusercontent.com/14798947/89718742-cd8bc600-d997-11ea-8ba8-c5111effe954.png)

Also, the selected maximum framerate will be respected.

**Comment by dschiller** [comment]
Amazing Work! Thanks a lot!!
