### ISSUE TITLE
Frequent issues when using a progress bar with the 2.0 Encoder, but fine with 1.0

### ISSUE THREAD

**Issue by KybernetikGames** [NickeManarin/ScreenToGif#580]
When I add a progress bar and save with the 2.0 encoder, it very often (but not always) causes severe artifacts when played (it never seems to happen without a progress bar):

![Recording 2 0](https://user-images.githubusercontent.com/43698611/72524121-f25e0600-38ac-11ea-9cb5-a223ba245fb6.gif)

But the 1.0 encoder doesn't have the same issue:

![Recording 1 0](https://user-images.githubusercontent.com/43698611/72524160-099cf380-38ad-11ea-9101-40b5143a2e91.gif)

I like the smaller file size of 2.0, but it's really annoying having to always check for this issue. I've uploaded the project file [here](https://drive.google.com/file/d/161ZhAgwyqBRmDxW41SdmPiEazE3UI62b/view?usp=sharing) in case that helps you reproduce it.

**Comment by NickeManarin** [comment]
Try changing the color of the progress bar to other color, not green. Green is used as the color marked as transparent, enabling some file size saving,

**Comment by KybernetikGames** [comment]
It would probably be good to have a warning about that when adding a progress bar. I've already used green ones on dozens of gifs so I can't exactly change to a different colour at this point.

**Comment by elexx** [comment]
I think you can also go the other way round: Change the color that marks transparent pixels. It's in the save-panel, Encode 2.0 under "GIF-Options"

**Comment by NickeManarin** [comment]
This issue was fixed, and it will be available with the next release.
You don't need to care about having the chroma key (known as 'dummy color' in older versions) as a color in the frame!

I developed from scratch the built-in encoders.

![EbkC_NIWsAEZ4Jn](https://user-images.githubusercontent.com/14798947/86027391-06369800-ba07-11ea-8b88-ca887024b945.png)

Octree (known as '2.0'):
![Octree](https://user-images.githubusercontent.com/14798947/86027454-1cdcef00-ba07-11ea-9d70-1e80225f624f.gif)

Neural (known as '1.0'):
![Neural](https://user-images.githubusercontent.com/14798947/86027528-34b47300-ba07-11ea-814d-470da123793c.gif)

You're still going to get the color shifts in the progress bar using the Neural quantizer, since that's how the encoder works. :/
