### ISSUE TITLE
Bitrate options for webm

### ISSUE THREAD

**Issue by ultrafine** [NickeManarin/ScreenToGif#641]
Webm is a great format but I feel like the default setting in ScreenToGif compresses too much. I've tried reading some of the encoding guides like [this](https://trac.ffmpeg.org/wiki/Encode/VP9) and [this](https://sites.google.com/a/webmproject.org/wiki/ffmpeg/vp9-encoding-guide), but apparently webm input screen in this program is a bit different so I have trouble applying those settings. It would be great if:

1. There's a GUI option for webm bitrate setting
or
2. Written guide for applying recommended VP9 settings for ScreenToGif

Also, most of those encoding guides recommend two-pass method. I don't know if ScreenToGif already supports it, but if it doesn't, it will be great to have two-pass encoding support too.

**Comment by NickeManarin** [comment]
For the bitrate, you should just add `-b:v 2M`  after the encoder `libvpx-vp9`.

![image](https://user-images.githubusercontent.com/14798947/80597518-56d94700-89fe-11ea-9935-18d7fbdce5f9.png)

As for the second pass, this needs to be implemented yet, because it is required a second call to FFmpeg passing a log file.

**Comment by ultrafine** [comment]
Thank you! It worked well. I'm looking forward to see two-pass encoding implemented since it's suppose to bring some quality increase.

May I ask one more question about the setting: '-pix_fmt yuv420p' option is there as a default, and from the search says it's 4:2:0 chroma subsampling, but I don't know how it affects webm file in real use. Is it okay to use presets without -pix_fmt yuv420p? I've noticed the file size is slightly smaller without it.

**Comment by NickeManarin** [comment]
`yuv420p` was added because it was the only format supported by some websites (Twitter for example). You can remove it, but it won't be able to upload in some websites.

As for the second pass, you should just add `-pass 2` to a command, and it will run the second pass:

![image](https://user-images.githubusercontent.com/14798947/81231821-3135da00-8fca-11ea-97e2-4ab63e75599c.png)

Also, click on the "Reset" icon to get the new default params, after the next update.  

![image](https://user-images.githubusercontent.com/14798947/81231975-75c17580-8fca-11ea-9332-3f16c64e1ca6.png)

(v2.24)
