### ISSUE TITLE
make selection window moveable in windows?

### ISSUE THREAD

**Issue by mnooblet** [NickeManarin/ScreenToGif#678]
it would be great if the window where you select the part of the screen to record would be moveable like other windows when you right click on it, this would make placing the window pixel perfect a lot easier than with mouse only :)

**Comment by NickeManarin** [comment]
I expanded the keyboard commands available in the selection mode of the new recorder UI to the capture mode of that same recorder and to the older recorder UI.

**Arrow keys**: Move the selected region around the screen.  
**Ctrl + Arrow keys**: Controls the resize of the Left/Top sides.  
**Shift + Arrow keys**: Controls the resize of the Right/Bottom sides.  
**Ctrl + Shift + Arrow key**s: Controls the resize of both sides.  

**+ Alt**: Instead of moving by 1px at time, moves by 5px.

Btw, during capture the resize it blocked.  

It only works when the recorder window has focus, so it should not get in the way of the app being captured.
