### ISSUE TITLE
Importing a mp4 with FFmpeg crops the end of the video

### ISSUE THREAD

**Issue by Garfounkel** [NickeManarin/ScreenToGif#780]
Importing a mp4 by drag and drop in the editor deletes the end of the video when using FFmpeg as the importer. For instance, I have a 8 seconds clip where only the first 7.1 seconds can be imported in ScreenToGif (the preview window shows a total duration of 7.1 seconds and the last frame is clearly not the correct one).

**Comment by NickeManarin** [comment]
Can you share your video? If not here, via any other method in [here.](www.screentogif.com/contact)

**Comment by Garfounkel** [comment]
I've attached the [video here](https://user-images.githubusercontent.com/10576004/105198058-91ab7e00-5b3d-11eb-823e-420f603bb295.mp4  
), thanks for your help!

**Comment by NickeManarin** [comment]
Thanks for uploading the video.

I fixed the issue. It was caused by a workaround for some issue of FFmpeg not loading the last few milliseconds of the video.
I was reducing the duration of the video more than needed.

![image](https://user-images.githubusercontent.com/14798947/105566632-f74d6500-5d0b-11eb-9691-fc8e0ec3e64f.png)
