### ISSUE TITLE
[Bug] KeypressOSD bugs

### ISSUE THREAD

**Issue by Kristinita** [NickeManarin/ScreenToGif#79]
### 1. Summary

Sometimes I get bad quality GIFs use ScreenToGIF if I record GIF with [**KeypressOSD**](https://autohotkey.com/boards/viewtopic.php?t=225) AutoHotkey script.

### 2. Expected behavior

Good GIF quality.

### 3. Actual behavior

+ [**Project**](http://jmp.sh/zaTaKpJ),
+ [**ScreenToGIF encoder**](http://i.imgur.com/wQwsoWR.gif) — I see nice image in my local [**PViewer**](https://sourceforge.net/projects/picoviewer/) program, but image nod displayed in any web hosting.
+ [**System encoder**](https://app.box.com/s/pz4z0wcn322drlqn9na4a62lcrzc6lvk) — nice image, but 150MB. Image hostings don't support very large images.
+ Legacy — bad quality:

![Legacy](http://i.imgur.com/76Px5gN.gif)

### 4. Steps to reproduce

I record and edit my GIF → I save my GIFs in different encoders → I get actual behavior.

### 5. Environment

**Operating system and version:**
Windows 10 Enterprise LTSB 64-bit EN
**ScreenToGIF:**
2.4.0.170115
**KeypressOSD:**
2.10

Thanks.

**Comment by NickeManarin** [comment]
The gif (from the ScreenToGif encoder) plays nicely on the link that you shared.

The gif (from the Legacy encoder) fails to render because the color being changed is close to the default dummy color (a color that will be represented as transparent), lime green. 

I downloaded the project so I can debug it. Thanks.

**Comment by NickeManarin** [comment]
I was able to identify and fix this bug. It happened because the encoder was set to use a dummy color, but it could not find when the perfect rectangle was introduced in a frame with no other pixel modification. 

When failing to find the dummy color in the color map, the index 0 was set as transparent. That killed the red color in the example project.

**Comment by Kristinita** [comment]
> The gif (from the ScreenToGif encoder) plays nicely on the link that you shared.

@NickeManarin, **<http://i.imgur.com/wQwsoWR.gif>** image successfully open for me in Chrome and Opera, but don't open in Firefox 51.0.1 (64-bit).
The problem reproduced for me in [**Safe Mode**](https://support.mozilla.org/en-US/kb/troubleshoot-firefox-issues-using-safe-mode) and in Firefox without plugins and user settings.

Firefox bug?

Thanks.

**Comment by NickeManarin** [comment]
@Kristinita Working alright with Edge.

**Comment by Kristinita** [comment]
@NickeManarin , is it Firefox bug or ScreenToGIF encoder bug?

The problem reproduce for me in other file, which I get in ScreenToGIF encoder:

+ Project: **<http://jmp.sh/32AvhlU>**,
+ GIF: **<http://i.imgur.com/V3axgYT.gif>**.

GIF not open in Firefox.

Thanks.

**Comment by NickeManarin** [comment]
Looks like a Firefox bug. If you open that gif on Firefox, press F12 to open the developers tool, go to the Network tab, refresh the page to detect the `GET` command.

Hover the cursor on top of the thumbnail of the `GET` entry, you can see that the gif plays nicely.

![image](https://cloud.githubusercontent.com/assets/14798947/22736675/83ed7ef8-ede6-11e6-90e9-3bb400d9de9b.png)

**Comment by Kristinita** [comment]
Bugzilla@Mozilla [**Bug 1338551**](https://bugzilla.mozilla.org/show_bug.cgi?id=1338551).

Thanks.
