### ISSUE TITLE
vertically flipped video when using System encoder

### ISSUE THREAD

**Issue by bunchofsage** [NickeManarin/ScreenToGif#97]
Saving a project as video will store it upside down: playback in VLC oder Windows Media Player has flipped video.
-------------
ScreenToGif Version: 2.5
Encoder: System (FFmpeg works fine though)
Win 10 Pro 64 Bit

**Comment by NickeManarin** [comment]
Strange, it was flipped to me before the supposed fix. What's different between our systems?

Windows 10 Pro x64
Build 14393.693

**Comment by bunchofsage** [comment]
Microsoft Windows 10 Pro x64
Version	10.0.10586 Build 10586

**Comment by NickeManarin** [comment]
This is now a setting that can be enabled/disabled.

**Comment by sralse** [comment]
Sorry to say so but with every encoder (system provided) I'm having the same issue. Altough with the ffmpeg encoder it worked like a charm. Microsoft Windows 10 Pro x64 Version 1709 Build 16299.248
Using your latest build as of the day of this comment.

**Comment by NickeManarin** [comment]
Yes, the problem still persists because I couldn't detect the cause. 
So, if you wish to flip the video, just tick the "flip the video (vertically)"

**Comment by sralse** [comment]
Okay, thanks.

**Comment by LosD** [comment]
@NickeManarin That's a workaround, not a fix. The bug is still there. Why was this closed?

**Comment by NickeManarin** [comment]
@LosD Because I'm not able to detect the reason behind it. I've tried but I couldn't find why it flips vertically in some computers. :/
Feel free to help, if possible.

**Comment by LosD** [comment]
@NickeManarin Sure, but it's still a bug, so IMHO it's a little weird to treat it like a closed bug.

Anyway, my computer is doing the same, if there is any kind of debug build and - output, or debug statements I could put in that'll help with finding the root cause, I'm more than willing to try stuff out.

BTW, I'm not at my computer right now, so I can't verify, but I believe the uncompressed option doesn't flip the output, as the only one.
